INSERT INTO NOTICES(CODE, TITLE, CONTENT, WRITER) VALUES('1161', 'HI~', 'æ»≥Á«œººø‰~', 'CHM');

DELETE FROM NOTICES WHERE WRITER = 'CHM';

SELECT * FROM NOTICES;

SELECT count(*) FROM( select ROW_NUMBER() OVER (ORDER BY REGDATE DESC) NUM, NOTICES_VIEW.* from notices_VIEW
WHERE title LIKE '%%') N

SELECT * FROM NOTICEFILES;

		SELECT COUNT(*) COUNT FROM( select ROW_NUMBER() OVER (ORDER BY REGDATE DESC) NUM,
		NOTICES_VIEW.* from notices_VIEW
		WHERE TITLE LIKE '%%') N